/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gvdecoder_BaslerController */

#ifndef _Included_gvdecoder_BaslerController
#define _Included_gvdecoder_BaslerController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gvdecoder_BaslerController
 * Method:    openCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_openCamera
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    closeCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_closeCamera
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    startFocus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_startFocus
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    stopFocus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_stopFocus
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    GetData
 * Signature: ([IIIIII)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_GetData
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    saveImages
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_saveImages
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    saveToCircularBufferMulti
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_saveToCircularBufferMulti
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setActiveCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setActiveCamera
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    saveToCircularBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_saveToCircularBuffer
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    saveToCircularBufferFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_saveToCircularBufferFilter
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    getCircularBufferStoredFrameNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_getCircularBufferStoredFrameNumber
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    getCircularBufferFrame
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_getCircularBufferFrame
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    loadConfigFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_loadConfigFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    writeStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_writeStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    switchCameraOrder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_switchCameraOrder
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    mirror
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_gvdecoder_BaslerController_mirror
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setExposeTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_gvdecoder_BaslerController_setExposeTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setFrameRate
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_gvdecoder_BaslerController_setFrameRate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setGainAuto
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gvdecoder_BaslerController_setGainAuto
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setGainValue
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setGainValue
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setTrigger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setTrigger
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setOffsets
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setOffsets
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setPosition
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setPosition
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    setParameters
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_setParameters
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    getParameters
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_BaslerController_getParameters
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    getSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gvdecoder_BaslerController_getSerialNumber
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    testCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gvdecoder_BaslerController_testCamera
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_BaslerController
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gvdecoder_BaslerController_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
