/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gvdecoder_0005cNativeSPEDecoder */

#ifndef _Included_gvdecoder_0005cNativeSPEDecoder
#define _Included_gvdecoder_0005cNativeSPEDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    UpdateImageArray
 * Signature: ([IIII)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_UpdateImageArray
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    JumpToFrame
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_JumpToFrame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    OpenImageFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_OpenImageFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    CloseImageFile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_CloseImageFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    FilterOperation
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_FilterOperation
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    ReturnSupportedFilters
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gvdecoder_0005cNativeSPEDecoder_ReturnSupportedFilters
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    ReturnFrameNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_ReturnFrameNumber
  (JNIEnv *, jobject);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    SumROIs
 * Signature: ([[ILjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_SumROIs
  (JNIEnv *, jobject, jobjectArray, jstring, jint, jint, jint);

/*
 * Class:     gvdecoder_0005cNativeSPEDecoder
 * Method:    ReturnXYBandsFrames
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_gvdecoder_0005cNativeSPEDecoder_ReturnXYBandsFrames
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
