/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSPEDecoder */

#ifndef _Included_NativeSPEDecoder
#define _Included_NativeSPEDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeSPEDecoder
 * Method:    UpdateImageArray
 * Signature: ([IIII)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_UpdateImageArray
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     NativeSPEDecoder
 * Method:    JumpToFrame
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_JumpToFrame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeSPEDecoder
 * Method:    OpenImageFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_OpenImageFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeSPEDecoder
 * Method:    CloseImageFile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_CloseImageFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeSPEDecoder
 * Method:    FilterOperation
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_FilterOperation
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     NativeSPEDecoder
 * Method:    ReturnSupportedFilters
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeSPEDecoder_ReturnSupportedFilters
  (JNIEnv *, jobject);

/*
 * Class:     NativeSPEDecoder
 * Method:    ReturnFrameNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_ReturnFrameNumber
  (JNIEnv *, jobject);

/*
 * Class:     NativeSPEDecoder
 * Method:    SumROIs
 * Signature: ([[ILjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_SumROIs
  (JNIEnv *, jobject, jobjectArray, jstring, jint, jint, jint);

/*
 * Class:     NativeSPEDecoder
 * Method:    ReturnXYBandsFrames
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_NativeSPEDecoder_ReturnXYBandsFrames
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
