/*
 * SaveImagesPanel.java
 *
 * Created on 09 January 2007, 10:03
 */

package gvdecoder;

/**
 *
 * @author  Gil
 */
public class SaveImagesPanel extends javax.swing.JPanel {
    Viewer2 vi;
    /** Creates new form SaveImagesPanel */
    public SaveImagesPanel(Viewer2 vi) {
        this.vi=vi;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        autoFileName = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        chooseFileName = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        directoryName = new javax.swing.JTextField();
        autoDirectoryName = new javax.swing.JButton();
        chooseDirectoryName = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        startRange = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endRange = new javax.swing.JTextField();
        useSingleFrame = new javax.swing.JCheckBox();
        useNavigatorRange = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AVIFPS = new javax.swing.JTextField();
        AVISaveAsDefault = new javax.swing.JButton();
        AVIGrayscale = new javax.swing.JRadioButton();
        AVIColor = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        ImageSeriesOutputType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        SeriesSaveAsDefault = new javax.swing.JButton();
        seriesIncludeHTMLViewer = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        movFPS = new javax.swing.JTextField();
        moveGrayscale = new javax.swing.JRadioButton();
        movColor = new javax.swing.JRadioButton();
        movQuality = new javax.swing.JComboBox();
        movCodec = new javax.swing.JComboBox();
        movSaveAsDefault = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        skipFrames = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sumFrames = new javax.swing.JTextField();
        applyDropFrames = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showDecorations = new javax.swing.JCheckBox();
        addFrameNumbers = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        setSizeAsShown = new javax.swing.JRadioButton();
        setSizeToMin = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        setOutputWidth = new javax.swing.JTextField();
        StartEncoding = new javax.swing.JButton();
        CancelEncoding = new javax.swing.JButton();
        SaveSettingsToDefault = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output File + Directory"));
        autoFileName.setText("Auto");
        autoFileName.setToolTipText("generates a unique name");
        autoFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFileNameActionPerformed(evt);
            }
        });

        fileName.setColumns(10);
        fileName.setText(".");
        fileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameActionPerformed(evt);
            }
        });

        chooseFileName.setText("choose");
        chooseFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileNameActionPerformed(evt);
            }
        });

        jLabel1.setText("name");

        jLabel2.setText("directory");

        directoryName.setColumns(10);
        directoryName.setText(".");
        directoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryNameActionPerformed(evt);
            }
        });

        autoDirectoryName.setText("Auto");
        autoDirectoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoDirectoryNameActionPerformed(evt);
            }
        });

        chooseDirectoryName.setText("choose");
        chooseDirectoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDirectoryNameActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(11, 11, 11))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(directoryName)
                    .add(fileName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(autoFileName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chooseFileName))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(autoDirectoryName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chooseDirectoryName)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fileName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(autoFileName)
                    .add(chooseFileName)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(directoryName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(autoDirectoryName)
                    .add(chooseDirectoryName)
                    .add(jLabel2)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Range"));
        jLabel3.setText("start");
        jLabel3.setToolTipText("first frame in series\n");

        startRange.setColumns(10);
        startRange.setText("1");
        startRange.setToolTipText("input starting frame");
        startRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRangeActionPerformed(evt);
            }
        });

        jLabel4.setText("end");

        endRange.setColumns(10);
        endRange.setText("-1");
        endRange.setToolTipText("input end frame");
        endRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endRangeActionPerformed(evt);
            }
        });

        useSingleFrame.setText("single");
        useSingleFrame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useSingleFrame.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useSingleFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSingleFrameActionPerformed(evt);
            }
        });

        useNavigatorRange.setText("From Nav.");
        useNavigatorRange.setToolTipText("Take range from zoomed region of navigator");
        useNavigatorRange.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useNavigatorRange.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useNavigatorRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useNavigatorRangeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startRange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endRange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(useSingleFrame)
                .add(23, 23, 23)
                .add(useNavigatorRange)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel3)
                .add(startRange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel4)
                .add(endRange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(useSingleFrame)
                .add(useNavigatorRange))
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setText("FPS");

        AVIFPS.setText("20");
        AVIFPS.setToolTipText("enter frames per second");
        AVIFPS.setMinimumSize(new java.awt.Dimension(22, 19));
        AVIFPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVIFPSActionPerformed(evt);
            }
        });

        AVISaveAsDefault.setText("save as default");
        AVISaveAsDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVISaveAsDefaultActionPerformed(evt);
            }
        });

        buttonGroup2.add(AVIGrayscale);
        AVIGrayscale.setToolTipText("encode from scaled data only (ignores decorations!)");
        AVIGrayscale.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        AVIGrayscale.setLabel("gray");
        AVIGrayscale.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AVIGrayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVIGrayscaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(AVIColor);
        AVIColor.setText("colour");
        AVIColor.setToolTipText("encode using colour information from displayed images\n");
        AVIColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        AVIColor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AVIColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVIColorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel11)
                .add(15, 15, 15)
                .add(AVIFPS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(AVIGrayscale)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(AVIColor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(AVISaveAsDefault)
                .add(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(AVIFPS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AVISaveAsDefault)
                    .add(AVIColor)
                    .add(AVIGrayscale))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("AVI", jPanel5);

        ImageSeriesOutputType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GIF", "JPG", "BMP", "TIF", "PNG" }));
        ImageSeriesOutputType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ImageSeriesOutputTypeItemStateChanged(evt);
            }
        });
        ImageSeriesOutputType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageSeriesOutputTypeActionPerformed(evt);
            }
        });

        jLabel12.setText("type");

        SeriesSaveAsDefault.setText("Save as default");
        SeriesSaveAsDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeriesSaveAsDefaultActionPerformed(evt);
            }
        });

        seriesIncludeHTMLViewer.setText("inlclude html viewer");
        seriesIncludeHTMLViewer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        seriesIncludeHTMLViewer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        seriesIncludeHTMLViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriesIncludeHTMLViewerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ImageSeriesOutputType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(seriesIncludeHTMLViewer)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(SeriesSaveAsDefault)
                .add(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ImageSeriesOutputType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(SeriesSaveAsDefault)
                    .add(seriesIncludeHTMLViewer))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Images", jPanel4);

        jPanel7.setToolTipText("Only supported if quicktime installed\n");
        jLabel13.setText("FPS");

        movFPS.setColumns(5);
        movFPS.setText("20");
        movFPS.setToolTipText("input frames per second");
        movFPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movFPSActionPerformed(evt);
            }
        });

        moveGrayscale.setToolTipText("uses scaled raw data only (decorations not supported!)");
        moveGrayscale.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        moveGrayscale.setLabel("gray");
        moveGrayscale.setMargin(new java.awt.Insets(0, 0, 0, 0));
        moveGrayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveGrayscaleActionPerformed(evt);
            }
        });

        movColor.setText("color");
        movColor.setToolTipText("Uses color from displayed image");
        movColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        movColor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        movColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movColorActionPerformed(evt);
            }
        });

        movQuality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "low", "med", "hi", "max" }));
        movQuality.setToolTipText("select encoding quality");
        movQuality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movQualityActionPerformed(evt);
            }
        });

        movCodec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cinepak", "animation", "H.263", "Sorensen", "Sorensen3", "mpeg-4" }));
        movCodec.setToolTipText("select encoder");
        movCodec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movCodecActionPerformed(evt);
            }
        });

        movSaveAsDefault.setFont(new java.awt.Font("Tahoma", 0, 10));
        movSaveAsDefault.setText("Save as default");
        movSaveAsDefault.setMargin(new java.awt.Insets(2, 5, 2, 5));
        movSaveAsDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movSaveAsDefaultActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movFPS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(moveGrayscale)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movColor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movQuality, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movCodec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(movSaveAsDefault)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(movFPS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(moveGrayscale)
                    .add(movColor)
                    .add(movQuality, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(movCodec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(movSaveAsDefault))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("mov", jPanel7);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Process (if supported)"));
        jLabel5.setText("skip");

        skipFrames.setColumns(5);
        skipFrames.setText("1");
        skipFrames.setToolTipText("use every n'th frame (1 for all)");
        skipFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipFramesActionPerformed(evt);
            }
        });

        jLabel6.setText("sum");
        jLabel6.setToolTipText("sums N frames (uses the summed value, 1 for no summing)");

        sumFrames.setColumns(5);
        sumFrames.setText("1");
        sumFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumFramesActionPerformed(evt);
            }
        });

        applyDropFrames.setText("Apply");
        applyDropFrames.setToolTipText("Will try to skip/sum frames if supported (uncheck for default behaviour)");
        applyDropFrames.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        applyDropFrames.setMargin(new java.awt.Insets(0, 0, 0, 0));
        applyDropFrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyDropFramesActionPerformed(evt);
            }
        });

        jLabel7.setText("drop frames");

        jLabel8.setText("decorations");

        showDecorations.setText("show all");
        showDecorations.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showDecorations.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showDecorations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDecorationsActionPerformed(evt);
            }
        });

        addFrameNumbers.setText("add framenumbers");
        addFrameNumbers.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addFrameNumbers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addFrameNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFrameNumbersActionPerformed(evt);
            }
        });

        jLabel9.setText("size");

        buttonGroup1.add(setSizeAsShown);
        setSizeAsShown.setText("as shown");
        setSizeAsShown.setToolTipText("set equal to display window");
        setSizeAsShown.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setSizeAsShown.setMargin(new java.awt.Insets(0, 0, 0, 0));
        setSizeAsShown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSizeAsShownActionPerformed(evt);
            }
        });

        buttonGroup1.add(setSizeToMin);
        setSizeToMin.setText("min");
        setSizeToMin.setToolTipText("set equal to the size of the data array");
        setSizeToMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setSizeToMin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        setSizeToMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSizeToMinActionPerformed(evt);
            }
        });

        jLabel10.setText("width=");

        setOutputWidth.setText("jTextField7");
        setOutputWidth.setToolTipText("enter image width (height set to 1:1 aspect ratio with image)");
        setOutputWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOutputWidthActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jLabel7)
                    .add(jLabel9))
                .add(24, 24, 24)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(showDecorations)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel6Layout.createSequentialGroup()
                            .add(applyDropFrames)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                            .add(jLabel5)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                        .add(jPanel6Layout.createSequentialGroup()
                            .add(setSizeAsShown)
                            .add(16, 16, 16))))
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(addFrameNumbers)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(skipFrames, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(16, 16, 16)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sumFrames, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(setSizeToMin)
                        .add(21, 21, 21)
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(setOutputWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(126, 126, 126))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(applyDropFrames)
                    .add(jLabel5)
                    .add(skipFrames, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(sumFrames, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(addFrameNumbers)
                    .add(showDecorations))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(setSizeAsShown)
                    .add(setSizeToMin)
                    .add(jLabel10)
                    .add(setOutputWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        StartEncoding.setBackground(new java.awt.Color(102, 255, 51));
        StartEncoding.setText("Start");
        StartEncoding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartEncodingActionPerformed(evt);
            }
        });

        CancelEncoding.setText("Cancel");
        CancelEncoding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelEncodingActionPerformed(evt);
            }
        });

        SaveSettingsToDefault.setText("Save as default");
        SaveSettingsToDefault.setToolTipText("save settings above as default settings ");
        SaveSettingsToDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSettingsToDefaultActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(StartEncoding)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CancelEncoding)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 135, Short.MAX_VALUE)
                        .add(SaveSettingsToDefault)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(StartEncoding)
                    .add(CancelEncoding)
                    .add(SaveSettingsToDefault))
                .add(13, 13, 13)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveSettingsToDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSettingsToDefaultActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_SaveSettingsToDefaultActionPerformed

    private void CancelEncodingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelEncodingActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_CancelEncodingActionPerformed

    private void StartEncodingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartEncodingActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_StartEncodingActionPerformed

    private void movSaveAsDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movSaveAsDefaultActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_movSaveAsDefaultActionPerformed

    private void movCodecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movCodecActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_movCodecActionPerformed

    private void movQualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movQualityActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_movQualityActionPerformed

    private void movColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movColorActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_movColorActionPerformed

    private void moveGrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveGrayscaleActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_moveGrayscaleActionPerformed

    private void movFPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movFPSActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_movFPSActionPerformed

    private void SeriesSaveAsDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeriesSaveAsDefaultActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_SeriesSaveAsDefaultActionPerformed

    private void seriesIncludeHTMLViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriesIncludeHTMLViewerActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_seriesIncludeHTMLViewerActionPerformed

    private void ImageSeriesOutputTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageSeriesOutputTypeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ImageSeriesOutputTypeActionPerformed

    private void ImageSeriesOutputTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ImageSeriesOutputTypeItemStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_ImageSeriesOutputTypeItemStateChanged

    private void AVISaveAsDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVISaveAsDefaultActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AVISaveAsDefaultActionPerformed

    private void AVIColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVIColorActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AVIColorActionPerformed

    private void AVIGrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVIGrayscaleActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AVIGrayscaleActionPerformed

    private void AVIFPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVIFPSActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AVIFPSActionPerformed

    private void setOutputWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOutputWidthActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_setOutputWidthActionPerformed

    private void setSizeToMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSizeToMinActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_setSizeToMinActionPerformed

    private void setSizeAsShownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSizeAsShownActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_setSizeAsShownActionPerformed

    private void addFrameNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFrameNumbersActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_addFrameNumbersActionPerformed

    private void showDecorationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDecorationsActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_showDecorationsActionPerformed

    private void sumFramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumFramesActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_sumFramesActionPerformed

    private void skipFramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipFramesActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_skipFramesActionPerformed

    private void applyDropFramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyDropFramesActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_applyDropFramesActionPerformed

    private void useNavigatorRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useNavigatorRangeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_useNavigatorRangeActionPerformed

    private void useSingleFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSingleFrameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_useSingleFrameActionPerformed

    private void endRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRangeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_endRangeActionPerformed

    private void startRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRangeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_startRangeActionPerformed

    private void directoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryNameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_directoryNameActionPerformed

    private void fileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_fileNameActionPerformed

    private void chooseDirectoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDirectoryNameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_chooseDirectoryNameActionPerformed

    private void autoDirectoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoDirectoryNameActionPerformed
// auto directory set
    }//GEN-LAST:event_autoDirectoryNameActionPerformed

    private void chooseFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileNameActionPerformed
//choose file name
    }//GEN-LAST:event_chooseFileNameActionPerformed

    private void autoFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFileNameActionPerformed
// Auto file name
    }//GEN-LAST:event_autoFileNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AVIColor;
    private javax.swing.JTextField AVIFPS;
    private javax.swing.JRadioButton AVIGrayscale;
    private javax.swing.JButton AVISaveAsDefault;
    private javax.swing.JButton CancelEncoding;
    private javax.swing.JComboBox ImageSeriesOutputType;
    private javax.swing.JButton SaveSettingsToDefault;
    private javax.swing.JButton SeriesSaveAsDefault;
    private javax.swing.JButton StartEncoding;
    private javax.swing.JCheckBox addFrameNumbers;
    private javax.swing.JCheckBox applyDropFrames;
    private javax.swing.JButton autoDirectoryName;
    private javax.swing.JButton autoFileName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton chooseDirectoryName;
    private javax.swing.JButton chooseFileName;
    private javax.swing.JTextField directoryName;
    private javax.swing.JTextField endRange;
    private javax.swing.JTextField fileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox movCodec;
    private javax.swing.JRadioButton movColor;
    private javax.swing.JTextField movFPS;
    private javax.swing.JComboBox movQuality;
    private javax.swing.JButton movSaveAsDefault;
    private javax.swing.JRadioButton moveGrayscale;
    private javax.swing.JCheckBox seriesIncludeHTMLViewer;
    private javax.swing.JTextField setOutputWidth;
    private javax.swing.JRadioButton setSizeAsShown;
    private javax.swing.JRadioButton setSizeToMin;
    private javax.swing.JCheckBox showDecorations;
    private javax.swing.JTextField skipFrames;
    private javax.swing.JTextField startRange;
    private javax.swing.JTextField sumFrames;
    private javax.swing.JCheckBox useNavigatorRange;
    private javax.swing.JCheckBox useSingleFrame;
    // End of variables declaration//GEN-END:variables

}
