def setupfftanalysis():
   id=w.openImageDecoder("ompro")
   mV=Matrix()
   mC=Matrix()
   mV.initialize(id,0,820,0,16,0,16)
   mC.initialize(id,0,820,0,16,16,32)
   traceV=mV.dat.section(5,5)
   traceC=mC.dat.section(5,5)
   savegnuplottraces(traceV,traceC,10,"omprotracedata.dat")
   mV.processInSpace() #get rid of holes
   mdv,mdc,mcorr=fftDomFreq(mV,mC,128,32,0.01)
   suppressNoisyMatrices(mcorr,mdv,mdc,0.9)
   delta(mcorr,0)
   mdc.subtract(mdv)
   absval(mdc)
   g=Gnuplot.Gnuplot(debug=1)
   #createmultiplot(mcorr,mdv,mdc,7,14,32,"omprotracedata.dat")
   return mcorr,mdc,mdv

def createmultiplot(M1,M2,M3,start,end,steplength,tracefilename):
  g('reset')
  g('unset multiplot')
  g('set nosurface')
  g('set contour')
  g('set cntrparam bspline')
  g('set cntrparam order 8')
  g('set cntrparam levels 10')
  g('set clabel')
  g('unset xtics')
  g('unset ytics')
  g('set yrange[15:0]')
  g('set origin 0.01,0.1')
  g('set size 0.9,0.9')
  g('unset key')
  g('set multiplot')
  g('set size 0.3,0.55')
  g('set cntrparam levels discrete 0.1,0.3,0.5')
  g('set view 0,0,1,1')
  for z in range(start,end):
    filestr="tmp%s.dat"%(z)
    writegnuplotdata(M1,z,filestr)
    str="set origin %s,%s"%(((z-start)*0.155),0.50)
    g(str)
    strtitle="set title '%s'"%(z*steplength*10)
    g(strtitle)
    cmdstr='splot "tmp%s.dat" w l'%(z)
    g(cmdstr)
    g('unset title')

  g('set cntrparam levels discrete 0.5,1,1.5,2,2.5')
  for z in range(start,end):
    filestr="vtmp%s.dat"%(z)
    writegnuplotdata(M2,z,filestr)
    str="set origin %s,%s"%(((z-start)*0.155),0.25)
    g(str)
    #strtitle="set title '%s'"%(z*steplength)
    #g(strtitle)
    cmdstr='splot "vtmp%s.dat" w l'%(z)
    g(cmdstr)
    #g('unset title')
 
  g('set cntrparam levels discrete 1,2,3,4,5')
  for z in range(start,end):
    filestr="ctmp%s.dat"%(z)
    writegnuplotdata(M3,z,filestr)
    str="set origin %s,%s"%(((z-start)*0.155),0.0)
    g(str)
    #strtitle="set title '%s'"%(z*steplength)
    #g(strtitle)
    cmdstr='splot "ctmp%s.dat" w l'%(z)
    g(cmdstr)
    #g('unset title')
  xstart=start*steplength*10
  xend=end*steplength*10
  g('set xrange[*:*]')
  g('set yrange[0:15]')
  g('set autoscale y')
  g('set xtics')
  str='set xrange[%s:%s]'%(xstart,xend)
  g(str)
  g('set origin 0.042,0')
  g('set size 0.992,0.2')
  str='plot "%s" u 1:2 w l, "%s" u 1:3 w l'%(tracefilename,tracefilename) 
  g(str)
